description: default config for CIFAR10 classification with resnet18
metrics_to_track:
- accuracy
entity: dalmiaman
project: cifar10
train_mode: train-val
val_mode: test

model:
    name: multiclass-classification
    batch_size: 512
    epochs: 35
    optimizer:
      name: AdamW
      args:
        lr: 0.0012
        weight_decay: 0.4
      scheduler:
        name: 1cycle
        update: batch
        params:
            max_lr: 0.03
            epochs: 35
            steps_per_epoch: 98
            pct_start: 0.3
            div_factor: 25
    loss:
      train-val:
        name: cross-entropy
        params:
            reduction: none
      test:
        name: cross-entropy
        params:
            reduction: none
    classes:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
      - 9
    save:
      period: 2
      monitor: accuracy
      monitor_mode: max
    load:
      version: null
      epoch: -1
      load_best: False
      resume_optimizer: False

network:
    name: neural_net
    params:
        config:
        - name: resnet18
          params:
            in_channels: 3
            pretrained: true
        - name: AdaptiveAvgPool2d
          params:
            output_size:
            - 1
            - 1
        - name: Flatten
          params: {}
        - name: Linear
          params:
            in_features: 512
            out_features: 10

data:
  data_type: image
  target_transform:
    name: classification
    params:
      classes:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
      - 9
  signal_transform:
    train-val:
    - name: Permute
      params:
        order:
          - 2
          - 0
          - 1
    - name: Rescale
      params:
        value: 255.
    - name: RandomHorizontalFlip
      params:
        p: 0.5
    - name: RandomCrop
      params:
        padding: 4
        size:
          - 32
          - 32
        padding_mode: reflect
    - name: Normalize
      params:
        mean:
          - 0.491
          - 0.482
          - 0.447
        std:
          - 0.247
          - 0.243
          - 0.261
    - name: RandomErasing
      params:
        p: 1.0
        ratio:
          - 1.
          - 1.
        scale:
          - 0.5
          - 0.5

    test:
    - name: Permute
      params:
        order:
          - 2
          - 0
          - 1
    - name: Rescale
      params:
        value: 255.
    - name: RandomHorizontalFlip
      params:
        p: 0.5
    - name: RandomCrop
      params:
        padding: 4
        size:
          - 32
          - 32
        padding_mode: reflect
    - name: Normalize
      params:
        mean:
          - 0.491
          - 0.482
          - 0.447
        std:
          - 0.247
          - 0.243
          - 0.261
    - name: RandomErasing
      params:
        p: 1.0
        ratio:
          - 1.
          - 1.
        scale:
          - 0.5
          - 0.5

  dataset:
    name: classification_dataset
    config:
      - name: CIFAR10
        version: default
    params: {}
  collate_fn:
    name: classification_collate
    params: {}
